# Site settings
title: DBAeyes
header-img: "img/autumn2.jpg"
tagline: "相遇在南十字星下"  
description: "Meet at the Southern Cross constellation(Crux)"  
baseurl: ""
url: "http://dbaeyes.me"  
#url: "http://azeril.me"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "David"
  email: renwei.chu@gmail.com
  bio: "上善若水"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: dbaeyes
twitter_username: dbaeyes  
github_username: dbaeyes  
facebook_username: dbaeyes  
weibo_username: poofly  
zhihu_username: dbaeyes  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Australia/Adelaide

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "David"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : David
  disqus :
      short_name : David

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation